service: events-dc-email

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    RECIPIENT_EMAIL: ${env:RECIPIENT_EMAIL}
    NODE_ENV: ${opt:stage, 'dev'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ses:SendEmail
            - ses:SendRawEmail
          Resource: "arn:aws:ses:${self:provider.region}:*:identity/*"
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "arn:aws:logs:${self:provider.region}:*:log-group:/aws/lambda/*"

functions:
  sendEmail:
    handler: functions/sendEmail.handler
    events:
      - http:
          path: send-email
          method: post
          cors: true
    environment:
      RECIPIENT_EMAIL: ${env:RECIPIENT_EMAIL}
    timeout: 30
    memorySize: 256